wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708597757.172903
    t:
      1:
      - 1
      - 5
      - 11
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      - 71
      - 83
      - 98
      2:
      - 1
      - 5
      - 11
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      - 71
      - 83
      - 98
      3:
      - 13
      - 23
      4: 3.8.18
      5: 0.16.3
      6: 4.33.2
      8:
      - 5
      13: linux-x86_64
