num_epochs: 30
batch_size: 32
optimizer:
  lr: 5e-5
  adam_epsilon: 1e-8
  weight_decay: 0.05
  warmup_ratio: 0.1
inference_params:
  q2a:
    num_beams: 5
    length_penalty: -1.0
  qr2a:
    num_beams: 5
    length_penalty: -1.0
  q2r:
    num_beams: 5
  q2ra:
    num_beams: 5
    max_length: 128
